### ISSUE TITLE
Does not work with the latest version of Winston

### ISSUE THREAD

**Issue by MohitKumar1991** [itsfadnis/datadog-winston#45]
I am getting this error on running with the latest version of datadog

`Datadog is a legacy winston transport. Consider upgrading: 
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
TypeError: this.transport.on is not a function
    at new LegacyTransportStream (/Users/mohitkumar/Documents/MagikInvest/processor-express/magik-payment-processor/node_modules/winston-transport/legacy.js:37:20)
    at DerivedLogger.add (/Users/mohitkumar/Documents/MagikInvest/processor-express/magik-payment-processor/node_modules/winston/lib/winston/logger.js:352:11)
    at Object.<anonymous> (/Users/mohitkumar/Documents/MagikInvest/processor-express/magik-payment-processor/src/utils/logger.ts:31:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mohitkumar/Documents/MagikInvest/processor-express/magik-payment-processor/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/yp/57zk1ww578sfd4gs82sbhndh0000gn/T/ts-node-dev-hook-26993806612835525.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/yp/57zk1ww578sfd4gs82sbhndh0000gn/T/ts-node-dev-hook-26993806612835525.js:114:20)
    at require.extensions.<computed> (/private/var/folders/yp/57zk1ww578sfd4gs82sbhndh0000gn/T/ts-node-dev-hook-26993806612835525.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/mohitkumar/Documents/MagikInvest/processor-express/magik-payment-processor/node_modules/ts-node-dev/lib/hook.js:63:13)
[ERROR] 17:00:21 TypeError: this.transport.on is not a function`

**Comment by MohitKumar1991** [comment]
Nevermind Version issue. Sorry for this. Please delete.
